name: Check CRD Version Update

on:
  pull_request:
    paths:
      - 'pkg/k8s/apis/cilium.io/client/crds/v1alpha1/*.yaml'

jobs:
  check-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Get all changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1

      - name: Check for CRD changes and version update
        run: |
          for changed_file in ${{ steps.changed-files.outputs.all }}; do
            if echo "$changed_file" | grep -q 'pkg/k8s/apis/cilium.io/client/crds/v1alpha1/'; then
              if [[ "$changed_file" == *"register.go" ]]; then
                # Logic to extract and compare version numbers
                old_version=$(git show ${{ github.event.pull_request.base.sha }}:$changed_file | grep 'CustomResourceDefinitionSchemaVersion' | awk -F'"' '{print $2}')
                new_version=$(grep 'CustomResourceDefinitionSchemaVersion' $changed_file | awk -F'"' '{print $2}')

                if [ "$old_version" == "$new_version" ]; then
                  echo "Error: CRD version not updated in $changed_file! Please update the CustomResourceDefinitionSchemaVersion."
                  exit 1
                fi
              fi
            fi
          done
