name: Check CRD Version Update
on:
  pull_request:
    paths:
      - 'pkg/k8s/apis/cilium.io/client/crds/v1alpha1/*.yaml'

jobs:
  check-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensure enough history is fetched for comparisons

      - name: Get changed files
        id: changed-files
        run: |
          changed_files=$(git diff --name-only HEAD^1 HEAD | xargs)
          echo "changed_files=${changed_files}" >> $GITHUB_ENV

      - name: Check for CRD changes and version update
        run: |
          if echo "${{ env.changed_files }}" | grep -q 'pkg/k8s/apis/cilium.io/client/crds/v1alpha1/'; then
            # Get the old_version from test-dev branch
            old_version=$(git show test-dev:pkg/k8s/apis/cilium.io/v1alpha1/register.go | grep 'CustomResourceDefinitionSchemaVersion' | awk -F'"' '{print $2}')

            echo "Old Version: $old_version"

            # Get the new_version from test-dev-2 branch
            new_version=$(git show test-dev-2:pkg/k8s/apis/cilium.io/v1alpha1/register.go | grep 'CustomResourceDefinitionSchemaVersion' | awk -F'"' '{print $2}')

            echo "Old Version: $new_version"

            if [ "$old_version" == "$new_version" ]; then
              echo "Error: CRD version not updated! Please update the CustomResourceDefinitionSchemaVersion in register.go"
              exit 1
            fi
          else
            echo "No changes in the CRD files"
          fi
