name: Check CRD Version Update
on:
  pull_request:
    paths:
      - 'pkg/k8s/apis/cilium.io/client/crds/v1alpha1/*.yaml'

jobs:
  check-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for CRD changes and version update
        run: |
          changed_files=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }})

          if echo "$changed_files" | grep -q 'pkg/k8s/apis/cilium.io/client/crds/v1alpha1/'; then
            if ! echo "$changed_files" | grep -q 'pkg/k8s/apis/cilium.io/v1alpha1/register.go'; then
              echo "Error: CRD files changed, but register.go not modified."
              exit 1
            fi
          else
            echo "No changes in the CRD files"
          fi
